sudo: false
language: scala
stages:
  - test
  - name: deploy
    if: branch = master AND NOT type IN (push, pull_request)

script: sbt +test

jobs:
  include:
    - stage: test
      jdk: oraclejdk8
    - stage: test
      jdk: openjdk8
      script: sbt clean coverage +test && sbt coverageReport coveralls
    - stage: deploy
      jdk: openjdk8
      script: |
        openssl aes-256-cbc -K $encrypted_3b6b964f9930_key -iv $encrypted_3b6b964f9930_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar -d &&
          tar xv -C travis -f travis/local.secrets.tar &&
          sbt +releaseEarly
env:
  global:
  - secure: sIFqC4HL5rbABrkce2Tdcpf0jC7O6ecjDPQlC+2gQLHuRUGDO0BIgzmjDxlyzKeX4zQEXqo5txP8qR3Lz7mVAFNZhN3CuawzhTvGmtlK7C8+7Y4l9c9UNlPBkxjDXF76/4mZaTMYxPjQslEOvvTGQxa/2Ic8nGeMoQThfgY4CQDUr6Ni4wmP/jOSGY6QMaASQnaGeYL8gZy4xK5AwQEHeALikaeiwOS3Ud6MUAoN3vTfxFkz7SYXCu5IDagU2aC79UFc7xjWrfdpONxhnP/hKTq+cDtjrR9yvq8OplkH+BPyVhw7AJQyOos5jcyMCn4W56Rzeq3uHDu13/AktyEtb/wCs2M4UJTrpN9spgJeGZuDv0pYtHae7PRrwvUT/uvxItJ2hI4lr/VIU2LsuCtZ/sEDjeSCV6jwHodj8HNHyxIGchh5JFRujeGniaBZRFHgvC/jOvQjr6DoavG5OsVWYJeWmVkZsI4RF2+r3ws5mGlMzK2JW+g5bsJhfnncpbTzf4t8TdbzsfkKWc5EntND4eQCHz7MZGFZMTkB9qBpBLG16T5HUpMztbkQ2OkGo/1IThlwsL8XbCkuFMOSGH+Lrlj+iIZGDuPzbavtIyWpgp1OEAcNfV3qY3wAbqdniMwGNpmAC9vhhVlSCxSfHGRYQl67FGm987MFZ0ZvceHIJNQ=
  - secure: nSnrYpOFdFj2JoK67O4d5EiC4ynnmPNSjcSV3s416H31MlcJBCHtVkSUdgv3htk8qAEZd7k0eNwag3oSMAawVg6NU1RVBSTy4ZYW3GFt7UqKZUwrP/sWOQydCzHZ+xfM9otmHy2paefrNPK46+QjyCuJxhH6HGL8iEHfWv4w54dEwGHYqcl9STGwVUnHlg+a86zMu/Jvm8ITDFUkjWUt/TIJ94WegrhH+iQJbHtu9wF4lg7nhAwlSKRyXS+xEXjnVZcdMNcnuBfF4D/z79O00Ko3MmzpQBxEjVxCwZzHY7aqCCz2z5ZFkkrQbKYsIjhdiS793Y5SRblZU5bb3mKFFjyYTtkuRh7EnfByn2BeNO9PK3GKjA3COYAMrebU5yxr1FavHD60prmTMErB8qpXl/2Cj/BjMaNOA6eHK49w+KZcZzvg7Pjs3Px/cg+RbV1A1YcZ5pNVB3WkK44nNAtWKJrmIX5xdomHtRwtcyMPwnvrbAgvHeSkcAkmlobupC6ZosXKZvx8ktTV6kSQYxU2IrFZytaK2GM1IiYsVNpJAYXDzMOD07ZtHZy100Rp1Klzy1rba8bTUN/tVvLw+5kI9MnkxusPlb4qQkZMAQtEN9wVr69gq+ZDEyKtcXuQ4WMTLbVI7O9fBFOu6PhsMhtu2JhZXWSgI1LxXU7TQLLovuw=
  - secure: SPcs5iWG9fv4iyDiOz1xpH90HN44vPHNDHooLIxFR1oYvx+GOwLNys6LMD42QAgm25VXhpcLyZQRfhHOxYhncwd0loIN58hccZGlPLjz2/MaJCZipq72lRR0wWHzPfZWCd7E26sfqQVLZ5S6XBpNFlFXftkeVAwh0hLZkyVtgLkAPl3XMyBcyZsjGGKft8wDEAXQ2mKU5aULivsnvmUNfNW5NIj4xS968tyOdoV7IssNOPo+MJ+/bLJ96FF1cz7+Tv9B6Vk3LQ3EXWDygKW8DjNjekvcGlbEnnVHHOW5cbzjU8Wjwzib0sUfKhGiHhLwGrJZ7cQHF+3JJ/moRaK161wInjTMVkjKUFFOOryczCKZEaZ+SPbiTbJt9tNiqQY2BU2YxuVDmkMyuXCG+pEhlLcXEw7XybW6nIf2h8s3nhgQOwnwK5o7ioBuP7Z4o0kQgzHJ//vjCK0z/Zm0unyRm+wLfPBihQu7rF5X7uGl8Q/3qK25o9IADl5fzMi1IaHfZL0DSls7WqDIGyoj6tJ7X/pZsTz20DQbR+hhYwN7MDcXhkVlB6e9C3MX3RzWAFXr8bhsGhF7335ilFL4gpQfnHDsZYWgb+3RtCrQraoh4FnTqR57bhmTz1HSWBFwwk/OLduitN4Tz3E25xK0UQcE5riv8CKpPA/OR4xWB2btVW8=
